import './globals.css';
import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import Navbar from '@/components/Navbar/Navbar';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300', '600', '700'],
  variable: '--font-poppins',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className={poppins.variable} lang="en">
      <body className="var(--font-poppins)">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
